GET http://localhost:5028/usuarios

###
POST http://localhost:5028/usuarios?nome=Lucas

###
GET http://localhost:5028/times

###
GET http://localhost:5028/times/2

###
POST http://localhost:5028/times/
Content-Type: application/json

{
    "Nome" : "Real Madrid",
    "Cidade" : "Madrid",
    "TitulosBrasileiros" : 0,
    "TitulosMundiais" : 10
}


###
PUT http://localhost:5028/times/3
Content-Type: application/json

{
    "Nome" : "Curintia",
    "Cidade" : "Sampa",
    "TitulosBrasileiros" : 99,
    "TitulosMundiais" : 999
}
